name: macro

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - python=3.7
  - pip

  - ipykernel
  - jupyterlab
  - nb_conda_kernels

  - pandas
  - xlrd
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - numba
  - matplotlib
  - seaborn
  - estimagic

  - black
  - flake8

  - pip:
    - robustats
