name: macro

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pip

  - ipykernel
  - jupyterlab
  - nb_conda_kernels

  - pandas
  - xlrd
  - numpy=1.19.1
  - scipy
  - scikit-learn
  - numba
  - matplotlib
  - seaborn

  - black
  - flake8

  - pip:
    - robustats
